/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-115838-g4e4444f97c-20240615"
#endif /* AVUTIL_FFVERSION_H */
